### ISSUE TITLE
How to extend deploy_cert hook with custom commands

### ISSUE THREAD

**Issue by tombreit** [rembik/dehydrated-hetzner-hook#1]
Dear rembik, 

thanks a lot for wiring together Hetzner and dehydreated. I successfully completed all tasks - except  adding custom commands to the deploy_cert hook. Basically, I just want to run a `apachectl graceful` after a cert is successfully renewed. 

In another project I extended the dehydrated `hook.sh` with my additions - but how accomplish this with `/etc/dehydrated/hooks/hetzner/hook.py`?

For now I added the following in `hooks.py`:
```
def deploy_cert(args):
    ...
    apache_restart = subprocess.check_output(['/usr/sbin/apachectl', 'graceful'])
    logger.debug(' + apache_restart output: {0}'.format(apache_restart))
    return

```

**Comment by rembik** [comment]
Nice to hear that the script is working for you, too.

Did you import the python module?
https://stackoverflow.com/questions/34222221/start-stop-apache-via-python-script

Because your question isn't really related to the basic function of that script, i will close this issue.

For greater deployment solutions have a look at my [automatically ansible provisioning script](https://github.com/rembik/ansible-role-letsencrypt) which is easy to extend and customize.

**Comment by tombreit** [comment]
Sorry, there must have been a misunderstanding. I just wanted to know if your ``hook.py`` is intended to be extended by your users to run arbitrary post-deploy-tasks (like the dehydrated upstream ``hooks.sh`` . This apache-thing was an example.

**Comment by rembik** [comment]
Absolutely, you can extend it in the manner like you could in the dehydrated example `hook.sh` script. 

In environments with more complex and different post-deploy-tasks it don't fits well, so I decided not to use it for this purpose.
