### ISSUE TITLE
Improvement: Speed up verification process

### ISSUE THREAD

**Issue by SQ-SEN** [rembik/dehydrated-hetzner-hook#10]
This is actually an improvement suggestion not a bug.

Currently if I try to get a wild card certificate I need two verification tokens, for example.com and *.example.com
Now I have lets say 10 domains which means 20 tokens. Currently the hook inserts one token, waits, inserts the next, waits, ... This way verification needs several hours cause the Hetzner server need a few minutes each time to propagate the change.

1st suggestion: Group tokens for the same domain and add them in one request
2nd suggestion: First add all tokens and then verify the propagation.

Especially the second suggestion will speed up the entire process by x*2 times (x=number of domains) for wildcard certs. 

With the automated renewal it usually doesn't matter if it takes 5 minutes or 5 hours but if I "quickly want to test something" it makes a huge difference.

However, thank you for your great work so far!

**Comment by rembik** [comment]
The hook script is highly dependent from the dehydrated hook api!
Because the hook script will be triggered for every certificate request the first suggestion isnt really worth the effort. But the second suggestion is already provided. Use the [HOOK_CHAIN](https://github.com/lukas2511/dehydrated/blob/master/docs/hook_chain.md) parameter for that.

**Comment by SQ-SEN** [comment]
Thanks, I'll try that. Should be exactly what I was looking for (just searched in the wrong spot).

**Comment by rembik** [comment]
I refactored the code today. Please update the git development branch and try it yourself. 
I already tried it and it works like a charm for me. ;)
