### ISSUE TITLE
Support _acme-challenge CNAME entries

### ISSUE THREAD

**Issue by fkroener** [rembik/dehydrated-hetzner-hook#2]
Hi, thanks for your hook, which works pretty well.

I'd like to ask whether it would be possible to use this hook with domains that aren't registered with hetzner via _acme-challenge CNAME entry.

Suppose I have

`example.com` with hetzner and
`some.subdomain.example.org` somewhere else, with 
`_acme-challenge.some.subdomain.example.org` CNAME `_acme-challenge.example.com`
so I could request certs for domains I don't have API access to.

I wonder whether I could just add `example.com`'s hetzner ID to `some.subdomain.example.org` json conf or (probably better) if the hook could itself look up the location and responsible domain via DNS.

**Comment by rembik** [comment]
Hi, it could be possible, but I'm not sure if the ACME API allows it, because the TXT-record response will show the other domain name, too.

manually added `example.org` CNAME entry looks like:
```
_acme-challenge.subdomain         IN CNAME   _acme-challenge.subdomain.example.com.
```

generated `example.com` TXT entry looks like:
```
_acme-challenge.subdomain         IN TXT         "_acme-challenge-token"
```

TXT response for `_acme-challenge.subdomain.example.org` looks like:

Type | Domain Name | TTL | Record
-- | -- | -- | --
TXT | _acme-challenge.subdomain.example.com | 24 hrs | _acme-challenge-token

Unfortunately, I don't have time for that at the moment. You could fork the code, try it out and make a pull request, if it works. Here are some approaches for improving `hook.py`: 

- look in manually added `domain_aliases` key in account config file for domain alias entry from 
`example.org` to `example.com` (automated dns lookup seems to be a little bit overloaded to test it, but of course you can write the code for that too)
```
"domain_aliases": {
    "example.org": "example.com"
},
```
- ensure to create/delete requested TXT records for `example.org` in `example.com` zone file

EDIT:  After what I read [here](https://www.eff.org/de/deeplinks/2018/02/technical-deep-dive-securing-automation-acme-dns-challenge-validation) it is possible!

**Comment by rembik** [comment]
#3

**Comment by fkroener** [comment]
Wow, thanks a lot for implementing it straight away.

I wonder whether it is necessary to include the own domain in the CNAME entry. In the end we just want to follow the CNAME to check if we have control at hetzner of the domain it is pointing at.

So `dns-01-auth.example.com`, `example.com` and of course your `some.subdomain.example.org.example.com` should work equally well.

**Comment by rembik** [comment]
Turns out it was quite straight forward. 

I choose to include the whole requested domain to the CNAME, because otherwise it didn’t work equally well in every case. An example for challenges with alternative names show what I mean.

created CNAME entry for `sub.example.org` and `example.org`:
```
_acme-challenge          IN CNAME   _acme-challenge.example.com.
_acme-challenge.sub      IN CNAME   _acme-challenge.example.com.
```
dehydrated command for challenging `example.com`, `example.org` and `sub.example.org`: 
```shell
$ HETZNER_USERNAME='your-hetzner-user' HETZNER_PASSWORD='your-hetzner-password' dehydrated -c -d 'example.com example.org sub.example.org' -t 'dns-01' -k '/etc/dehydrated/hooks/hetzner/hook.py'
```
generated TXT records for `example.com`, `example.org` and `sub.example.org` before ACME validation:
```
_acme-challenge          IN TXT     "e8hcebbxR202sHbE5Bx4wVlkwP49MNMQ2RWtoObZRQ0"
_acme-challenge          IN TXT     "P49MNMQ2RWtoObZRQ0e8hcebbxR202sHbE5Bx4wVlkw"
_acme-challenge          IN TXT     "HbE5Bx4wVlkP49MNMQ2RWtoObZRQ0e8hcebbxR202sw"
```

**Comment by fkroener** [comment]
Hmm, I'd have thought that wouldn't be an issue and letsencrypt would just continue checking the TXT entries, until it found a matching one.

At least when requesting a wildcard cert with `example.com` and `*.example.com` I had two TXT entries as well and it appeared to work?

[acme-dns](https://github.com/joohoi/acme-dns) appears to be doing something similar.

**Comment by rembik** [comment]
Ahh ok, but it looks not well. ;)
If you test it, I will remove the CNAME restriction.

**Comment by fkroener** [comment]
Unfortunately I don't have access to the machine right now.

But as per [dev comment](https://community.letsencrypt.org/t/two-acme-challenge-dns-records-and-letsencrypt-failing-with-dns-problem-server-failure-at-resolver-looking-up-txt-for-acme-challenge/54260) I'd expect it to work. :)

**Comment by rembik** [comment]
Done. #4

**Comment by fkroener** [comment]
Thanks a lot, I'll test it later and report.

**Comment by fkroener** [comment]
Testing with:
`example.com` hosted at the robot, requesting: 
`example.com some.sub.example.com sub.domain.example.org *.example.com *.some.sub.example.com *.sub.domain.example.org`
appears to work here - at least with the staging API.

So, thanks again. :)

Can we have a release?

**Comment by rembik** [comment]
with pleasure...
What do you mean with „have a release“?
I already merged it in the master branch after I tested it myself. 
For such small project it doesn‘t need versioning with tags, isn‘t it?

**Comment by fkroener** [comment]
Hmm, I'm not entirely sure.
With tags I could properly install the hook system-wide without having to worry about changes.
I thought I used your 1.0 release on the other server, but I was probably using git.
